// AUTO-GENERATED from catalogo_rubros_ikusi.xlsx
// Do not edit by hand; regenerate from the source Excel when the client updates nomenclature.

export type Rubro = {
  rubro_id: string;
  nombre: string;
  centro?: string | null;
  regla?: string | null;
  metadata?: Record<string, any> | null;
};

export const RUBROS: Rubro[] = [
  {
    rubro_id: `RB0001`,
    nombre: `Costo mensual de ingenieros asignados al servicio según % de asignación.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0002`,
    nombre: `Perfil senior técnico con responsabilidad de coordinación técnica.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0003`,
    nombre: `Gestión operativa, relación con cliente, reportes, SLAs.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0004`,
    nombre: `On‑call, fines de semana, festivos.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0005`,
    nombre: `Soporte temporal bajo nómina interna.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0006`,
    nombre: `Recursos por demanda no nómina.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0007`,
    nombre: `Reuniones periódicas de servicio con cliente (operativas/ejecutivas).`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0008`,
    nombre: `Generación y distribución de informes de desempeño.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0009`,
    nombre: `Revisión de cumplimiento, controles, evidencias.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0010`,
    nombre: `Cursos y certificaciones relevantes para el servicio.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0011`,
    nombre: `Horas de mantenimiento programado.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0012`,
    nombre: `Atención a incidentes / fallas.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0013`,
    nombre: `Técnicos terceros on‑site por demanda.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0014`,
    nombre: `Taxis, peajes, combustible según política.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0015`,
    nombre: `Alojamiento y alimentación de técnicos en sitio.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0016`,
    nombre: `Cables, conectores, bridas, herramientas menores.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0017`,
    nombre: `Herramientas NMS/APM/Logs.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0018`,
    nombre: `Plataforma ITSM (SaaS).`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0019`,
    nombre: `Equipos de prueba, bancos de ensayo.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0020`,
    nombre: `Renovación de laptops/workstations (3 años).`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0021`,
    nombre: `Routers/switches/APs/antenas instalados en cliente.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0022`,
    nombre: `Renovación de soporte HW/SW (SmartNet, etc.).`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0023`,
    nombre: `SaaS/IaaS/PaaS asociados al servicio.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0024`,
    nombre: `Costos energéticos y acondicionamiento.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0025`,
    nombre: `Arrendamiento de espacio en DC/edge.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0026`,
    nombre: `Copias y recuperación ante desastres.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0027`,
    nombre: `MPLS/Internet/SD‑WAN.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0028`,
    nombre: `Plataformas de voz/video/mensajería.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0029`,
    nombre: `Líneas celulares del servicio.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0030`,
    nombre: `Servicios de numeración y troncales SIP.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0031`,
    nombre: `Servicios SOC/EDR/SIEM.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0032`,
    nombre: `Evaluaciones periódicas de seguridad.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0033`,
    nombre: `Controles y auditorías normativas.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0034`,
    nombre: `Inventario de repuestos críticos.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0035`,
    nombre: `Gestión de devoluciones a fabricante.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0036`,
    nombre: `Paquetería de equipos y partes.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0037`,
    nombre: `Penalties por incumplimiento de SLAs.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0038`,
    nombre: `Fondo de contingencias para eventos mayores.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0039`,
    nombre: `Coberturas de equipos/operación.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0040`,
    nombre: `Soporte de gobierno y metodología.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0041`,
    nombre: `Procesamiento y conciliación de facturas.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0042`,
    nombre: `Asientos, conciliaciones, cierres.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0043`,
    nombre: `Herramientas de oficina/gestión.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0044`,
    nombre: `Revisión y gestión contractual.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0045`,
    nombre: `Renovaciones y auditorías externas.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0046`,
    nombre: `Iniciativas de optimización.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0047`,
    nombre: `Medición periódica de CSAT/OSAT.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0048`,
    nombre: `Licencias/uso para planificación/PPM.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0049`,
    nombre: `Extracción/ingesta de Hoja de Costos.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0050`,
    nombre: `Integraciones contables/facturación.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0051`,
    nombre: `Sincronización maestros (clientes/proveedores).`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0052`,
    nombre: `Cálculo contable de activos HW.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0053`,
    nombre: `Amortización de licencias perpetuas.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0054`,
    nombre: `Servicios de NOC (turnos).`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0055`,
    nombre: `Triaging, escalamiento, reportes.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0056`,
    nombre: `Capacity planning de red/infra.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0057`,
    nombre: `Teams/Zoom/Meet, grabaciones, PBX cloud.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0058`,
    nombre: `Drive/SharePoint/OneDrive.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0059`,
    nombre: `Exchange/Google Workspace.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0060`,
    nombre: `Viajes no asociados a intervención de campo.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0061`,
    nombre: `Reuniones ejecutivas/operativas en cliente.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0062`,
    nombre: `Bodegas y gestión de inventario.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0063`,
    nombre: `Herramienta de gestión de almacén.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0064`,
    nombre: `Coberturas de pérdida/daño.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0065`,
    nombre: `Soporte/firmware/feeds de seguridad.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0066`,
    nombre: `Controladores/licencias por dispositivo.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0067`,
    nombre: `Protección endpoints del servicio.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0068`,
    nombre: `Métricas y evidencias contractuales.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0069`,
    nombre: `Compromisos entre áreas internas.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0070`,
    nombre: `Pruebas de nuevas herramientas o procesos.`,
    centro: null,
    regla: null,
    metadata: null,
  },
  {
    rubro_id: `RB0071`,
    nombre: `Bots, scripts, detección de anomalías.`,
    centro: null,
    regla: null,
    metadata: null,
  },
];