openapi: 3.0.3
info:
  title: Portfolio Forecast API
  description: |
    API for aggregated portfolio-level forecast data and bulk upsert operations.
    Supports DashboardV2 with optimistic concurrency, idempotency, and audit logging.
  version: 1.0.0
  contact:
    name: API Support
    email: api-support@example.com

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://api-staging.example.com/v1
    description: Staging server

paths:
  /portfolio/forecast:
    get:
      summary: Get aggregated portfolio forecast
      description: |
        Returns consolidated forecast data across all projects for specified time period.
        Includes planned, actual, forecast values plus variance calculations.
        Single-call aggregation optimized for dashboard consumption.
      operationId: getPortfolioForecast
      tags:
        - Portfolio Forecast
      parameters:
        - name: year
          in: query
          required: true
          description: Fiscal year for forecast data
          schema:
            type: integer
            minimum: 2020
            maximum: 2100
            example: 2024
        - name: months
          in: query
          required: true
          description: Number of months to include (1-60)
          schema:
            type: integer
            minimum: 1
            maximum: 60
            example: 12
        - name: projectIds
          in: query
          required: false
          description: Optional filter by specific project IDs (comma-separated)
          schema:
            type: string
            example: "proj-123,proj-456"
        - name: rubroIds
          in: query
          required: false
          description: Optional filter by canonical rubro IDs (comma-separated)
          schema:
            type: string
            example: "rubro-001,rubro-002"
      responses:
        '200':
          description: Successful response with forecast data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PortfolioForecastResponse'
        '400':
          description: Invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - BearerAuth: []

  /portfolio/bulk-upsert-forecast:
    post:
      summary: Bulk upsert forecast values
      description: |
        Idempotent bulk update/insert of forecast cells.
        Supports optimistic concurrency via expected_last_updated.
        Returns per-item status for partial success handling.
      operationId: bulkUpsertForecast
      tags:
        - Portfolio Forecast
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkUpsertRequest'
      responses:
        '200':
          description: Bulk upsert completed (may include partial failures)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkUpsertResponse'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict - optimistic concurrency violation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    PortfolioForecastResponse:
      type: object
      required:
        - metadata
        - summary
        - rubros
        - projects
      properties:
        metadata:
          type: object
          required:
            - generatedAt
            - year
            - months
            - currency
          properties:
            generatedAt:
              type: string
              format: date-time
              description: Timestamp when response was generated
              example: "2024-01-15T10:30:00Z"
            year:
              type: integer
              example: 2024
            months:
              type: integer
              example: 12
            currency:
              type: string
              example: "USD"
              enum: ["USD", "MXN", "EUR"]
            filters:
              type: object
              properties:
                projectIds:
                  type: array
                  items:
                    type: string
                rubroIds:
                  type: array
                  items:
                    type: string
        summary:
          $ref: '#/components/schemas/ForecastSummary'
        rubros:
          type: array
          description: Forecast data grouped by canonical rubro
          items:
            $ref: '#/components/schemas/RubroForecast'
        projects:
          type: array
          description: Forecast data grouped by project
          items:
            $ref: '#/components/schemas/ProjectForecast'

    ForecastSummary:
      type: object
      description: Portfolio-level summary metrics
      required:
        - totalPlanned
        - totalActual
        - totalForecast
        - variance
      properties:
        totalPlanned:
          type: integer
          description: Total planned amount in cents
          example: 1000000
        totalActual:
          type: integer
          description: Total actual amount in cents
          example: 850000
        totalForecast:
          type: integer
          description: Total forecast amount in cents
          example: 950000
        variance:
          type: integer
          description: Variance (actual - planned) in cents
          example: -50000
        variancePercent:
          type: number
          format: float
          description: Variance as percentage
          example: -5.0
        runwayMonths:
          type: number
          format: float
          description: Estimated runway in months
          example: 8.5
        budgetUtilization:
          type: number
          format: float
          description: Budget utilization percentage
          example: 85.0

    RubroForecast:
      type: object
      required:
        - canonicalId
        - name
        - category
        - monthlyData
        - totals
      properties:
        canonicalId:
          type: string
          description: Canonical rubro identifier
          example: "rubro-001"
        name:
          type: string
          description: Rubro display name
          example: "Professional Services"
        category:
          type: string
          description: Rubro category
          example: "Services"
          enum: ["Services", "Infrastructure", "Personnel", "Other"]
        monthlyData:
          type: array
          description: Monthly forecast values
          items:
            $ref: '#/components/schemas/MonthlyForecast'
        totals:
          $ref: '#/components/schemas/ForecastTotals'
        last_updated:
          type: string
          format: date-time
          description: Last update timestamp for optimistic concurrency
          example: "2024-01-15T10:25:00Z"

    ProjectForecast:
      type: object
      required:
        - projectId
        - projectName
        - rubros
        - totals
      properties:
        projectId:
          type: string
          example: "proj-123"
        projectName:
          type: string
          example: "Infrastructure Modernization"
        rubros:
          type: array
          description: Rubros within this project
          items:
            $ref: '#/components/schemas/RubroForecast'
        totals:
          $ref: '#/components/schemas/ForecastTotals'

    MonthlyForecast:
      type: object
      required:
        - monthIndex
        - planned
        - actual
        - forecast
      properties:
        monthIndex:
          type: integer
          description: Zero-based month index
          minimum: 0
          maximum: 59
          example: 0
        monthLabel:
          type: string
          description: Display label (e.g., "Jan 2024")
          example: "Jan 2024"
        planned:
          type: integer
          description: Planned amount in cents
          example: 50000
        actual:
          type: integer
          description: Actual amount in cents
          example: 45000
        forecast:
          type: integer
          description: Forecast amount in cents
          example: 48000
        variance:
          type: integer
          description: Variance (actual - planned) in cents
          example: -5000

    ForecastTotals:
      type: object
      required:
        - totalPlanned
        - totalActual
        - totalForecast
        - totalVariance
      properties:
        totalPlanned:
          type: integer
          example: 600000
        totalActual:
          type: integer
          example: 540000
        totalForecast:
          type: integer
          example: 576000
        totalVariance:
          type: integer
          example: -60000

    BulkUpsertRequest:
      type: object
      required:
        - idempotencyKey
        - items
      properties:
        idempotencyKey:
          type: string
          format: uuid
          description: Client-generated idempotency key for deduplication
          example: "550e8400-e29b-41d4-a716-446655440000"
        items:
          type: array
          minItems: 1
          maxItems: 1000
          description: Forecast cells to upsert (max 1000 per request)
          items:
            $ref: '#/components/schemas/ForecastUpsertItem'

    ForecastUpsertItem:
      type: object
      required:
        - projectId
        - canonicalRubroId
        - monthIndex
        - value
        - valueType
      properties:
        projectId:
          type: string
          example: "proj-123"
        canonicalRubroId:
          type: string
          description: Must use server-provided canonical ID
          example: "rubro-001"
        monthIndex:
          type: integer
          minimum: 0
          maximum: 59
          example: 0
        value:
          type: integer
          description: Value in cents
          example: 50000
        valueType:
          type: string
          enum: ["forecast", "actual"]
          description: Type of value being updated
          example: "forecast"
        expected_last_updated:
          type: string
          format: date-time
          description: Expected last update time for optimistic concurrency
          example: "2024-01-15T10:25:00Z"

    BulkUpsertResponse:
      type: object
      required:
        - idempotencyKey
        - totalItems
        - successCount
        - failureCount
        - results
      properties:
        idempotencyKey:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        totalItems:
          type: integer
          example: 100
        successCount:
          type: integer
          example: 98
        failureCount:
          type: integer
          example: 2
        results:
          type: array
          description: Per-item status
          items:
            $ref: '#/components/schemas/UpsertResult'
        auditLogId:
          type: string
          description: Audit log record ID
          example: "audit-550e8400"

    UpsertResult:
      type: object
      required:
        - index
        - status
      properties:
        index:
          type: integer
          description: Index in original request items array
          example: 0
        status:
          type: string
          enum: ["success", "conflict", "error"]
          example: "success"
        message:
          type: string
          description: Optional error/conflict message
          example: "Conflict: expected_last_updated mismatch"
        current_last_updated:
          type: string
          format: date-time
          description: Current last_updated value (on conflict)
          example: "2024-01-15T10:30:00Z"

    ConflictResponse:
      type: object
      required:
        - error
        - conflictingItems
      properties:
        error:
          type: string
          example: "Optimistic concurrency conflict"
        conflictingItems:
          type: array
          items:
            type: object
            properties:
              index:
                type: integer
              expectedTimestamp:
                type: string
                format: date-time
              currentTimestamp:
                type: string
                format: date-time

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          example: "BadRequest"
        message:
          type: string
          example: "Invalid year parameter"
        details:
          type: object
          description: Additional error context
