name: Configure AWS via OIDC (local)
description: Assume an AWS IAM role using GitHub OIDC and export temp credentials
inputs:
  role_arn:
    description: AWS role ARN to assume
    required: true
  aws_region:
    description: AWS region
    required: true
  session_name:
    description: Session name
    default: "gh-oidc-${{ github.run_id }}"
  duration_seconds:
    description: Session duration
    default: "3600"
outputs:
  aws_access_key_id:
    description: AWS access key ID
    value: ${{ steps.export.outputs.aws_access_key_id }}
  aws_secret_access_key:
    description: AWS secret access key
    value: ${{ steps.export.outputs.aws_secret_access_key }}
  aws_session_token:
    description: AWS session token
    value: ${{ steps.export.outputs.aws_session_token }}
runs:
  using: composite
  steps:
    - name: Sanity & region
      shell: bash
      run: |
        set -euo pipefail
        [ -z "${{ inputs.role_arn }}" ] && { echo "role_arn missing"; exit 1; }
        [ -z "${{ inputs.aws_region }}" ] && { echo "aws_region missing"; exit 1; }
        echo "AWS_DEFAULT_REGION=${{ inputs.aws_region }}" >> "$GITHUB_ENV"

    - name: Request OIDC token
      id: oidc
      shell: bash
      run: |
        set -euo pipefail
        token_url="$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com"
        OIDC_RESP=$(curl -sfL -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$token_url")
        OIDC_TOKEN=$(python -c "import json,sys; print(json.load(sys.stdin)['value'])" <<<"$OIDC_RESP")
        [ -z "$OIDC_TOKEN" ] && { echo "OIDC token missing"; exit 1; }
        echo "token=$OIDC_TOKEN" >> "$GITHUB_OUTPUT"

    - name: Assume role with web identity
      id: export
      shell: bash
      run: |
        set -euo pipefail
        CREDS=$(aws sts assume-role-with-web-identity \
          --role-arn "${{ inputs.role_arn }}" \
          --role-session-name "${{ inputs.session_name }}" \
          --web-identity-token "${{ steps.oidc.outputs.token }}" \
          --duration-seconds "${{ inputs.duration_seconds }}" \
          --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
          --output text)
        IFS=$'\t' read AKID SAK STK <<<"$CREDS"
        echo "::add-mask::$AKID"
        echo "::add-mask::$SAK"
        echo "::add-mask::$STK"
        echo "aws_access_key_id=$AKID" >> "$GITHUB_OUTPUT"
        echo "aws_secret_access_key=$SAK" >> "$GITHUB_OUTPUT"
        echo "aws_session_token=$STK" >> "$GITHUB_OUTPUT"
        echo "AWS_ACCESS_KEY_ID=$AKID" >> "$GITHUB_ENV"
        echo "AWS_SECRET_ACCESS_KEY=$SAK" >> "$GITHUB_ENV"
        echo "AWS_SESSION_TOKEN=$STK" >> "$GITHUB_ENV"

    - name: Verify identity
      shell: bash
      run: aws sts get-caller-identity
