/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description Retrieves a paginated list of all projects with optional filtering
         */
        get: operations["listProjects"];
        put?: never;
        /**
         * Create new project
         * @description Creates a new project with initial configuration and financial parameters
         */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/handoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process project handoff
         * @description Registers the handoff of a project from sales to service delivery with budget distribution
         */
        post: operations["createHandoff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/rubros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get budget rubros catalog
         * @description Retrieves the complete catalog of available budget rubros (line items)
         */
        get: operations["listRubros"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/rubros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List project rubros
         * @description Gets all budget rubros associated with a specific project
         */
        get: operations["listProjectRubros"];
        put?: never;
        /**
         * Add rubro to project
         * @description Associates a budget rubro with a specific project and defines execution parameters
         */
        post: operations["createProjectRubro"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/allocations:bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Bulk update allocations
         * @description Updates budget allocations for multiple rubros in a single operation
         */
        put: operations["bulkUpdateAllocations"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project financial plan
         * @description Retrieves the financial plan for a specific project and month, including planned costs breakdown
         */
        get: operations["getProjectPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest payroll data
         * @description Imports payroll data for a specific month to compare against budget
         */
        post: operations["ingestPayroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/close-month": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close monthly period
         * @description Closes the financial period for a month and generates coverage report
         */
        post: operations["closeMonth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/report/cobertura": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get coverage report
         * @description Retrieves coverage analysis across projects and months
         */
        get: operations["getCoverageReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List adjustments
         * @description Retrieves list of budget adjustments with optional filtering
         */
        get: operations["listAdjustments"];
        put?: never;
        /**
         * Create budget adjustment
         * @description Creates a budget adjustment with pro-rata distribution when needed
         */
        post: operations["createAdjustment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List movements
         * @description Retrieves list of financial movements with filtering options
         */
        get: operations["listMovements"];
        put?: never;
        /**
         * Create financial movement
         * @description Records a financial movement that requires approval workflow
         */
        post: operations["createMovement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movements/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve movement
         * @description Approves a pending financial movement
         */
        post: operations["approveMovement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movements/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject movement
         * @description Rejects a pending financial movement with reason
         */
        post: operations["rejectMovement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get financial alerts
         * @description Retrieves active financial alerts for budget overruns, coverage issues, etc.
         */
        get: operations["listAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List providers
         * @description Retrieves list of registered providers
         */
        get: operations["listProviders"];
        put?: never;
        /**
         * Create provider
         * @description Registers a new provider/vendor in the system
         */
        post: operations["createProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prefacturas/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prefactura webhook
         * @description Receives prefactura events from external systems for automatic processing
         */
        post: operations["prefacturaWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProjectCreate: {
            /** @description Project name */
            name: string;
            /** @description Unique project code */
            code: string;
            /** @description Client name */
            client: string;
            /**
             * Format: date
             * @description Project start date
             */
            start_date: string;
            /**
             * Format: date
             * @description Project end date
             */
            end_date: string;
            /**
             * @description Project currency
             * @enum {string}
             */
            currency: "USD" | "EUR" | "MXN";
            /** @description Total budget amount (MOD - Monto Original Dealsheet) */
            mod_total: number;
            /** @description Project description */
            description?: string;
        };
        Project: components["schemas"]["ProjectCreate"] & {
            /** @description Unique project identifier */
            id: string;
            /**
             * @description Current project status
             * @enum {string}
             */
            status: "active" | "completed" | "on_hold" | "cancelled";
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        ProjectList: {
            data?: components["schemas"]["Project"][];
            /** @description Total number of projects */
            total?: number;
            /** @description Page size limit */
            limit?: number;
            /** @description Pagination offset */
            offset?: number;
        };
        Handoff: {
            /** @description Total budget being handed off */
            mod_total: number;
            /** @description Percentage allocated to engineers */
            pct_ingenieros: number;
            /** @description Percentage allocated to SDM (Service Delivery Management) */
            pct_sdm: number;
            /**
             * Format: email
             * @description Email of person accepting handoff
             */
            aceptado_por: string;
            /**
             * Format: date
             * @description Date of handoff
             */
            fecha_handoff: string;
            /** @description Additional notes */
            notas?: string;
        };
        RubroCreate: {
            /** @description Reference to catalog rubro */
            rubro_id: string;
            /** @description Total amount for this rubro */
            monto_total: number;
            /**
             * @description Execution type - monthly, one-time, or milestone-based
             * @enum {string}
             */
            tipo_ejecucion: "mensual" | "puntual" | "por_hito";
            /** @description Scheduled months in YYYY-MM format */
            meses_programados?: string[];
            /** @description Additional notes */
            notas?: string;
        };
        Rubro: {
            /** @description Unique rubro identifier */
            id?: string;
            /** @description Associated project (if project-specific) */
            project_id?: string;
            /** @description Reference to catalog rubro */
            rubro_id?: string;
            /** @description Rubro code */
            code?: string;
            /** @description Rubro name */
            nombre?: string;
            /** @description Category */
            categoria?: string;
            /** @description Total amount */
            monto_total?: number;
            /**
             * @description Execution type
             * @enum {string}
             */
            tipo_ejecucion?: "mensual" | "puntual" | "por_hito";
            /** @description Scheduled months */
            meses_programados?: string[];
            /** @description Monthly amount (for mensual type) */
            monto_mensual?: number;
            /** @description Description */
            descripcion?: string;
            /** Format: date-time */
            created_at?: string;
        };
        RubroList: {
            data?: components["schemas"]["Rubro"][];
            total?: number;
        };
        AllocationBulk: {
            allocations: {
                rubro_id: string;
                mes: string;
                monto_planeado: number;
            }[];
        };
        PlanMes: {
            /** @description Project identifier */
            project_id?: string;
            /** @description Month in YYYY-MM format */
            mes?: string;
            /** @description Planned engineering costs */
            plan_ing?: number;
            /** @description Planned SDM costs */
            plan_sdm?: number;
            /** @description Non-recurring costs breakdown */
            non_recurrentes?: {
                rubro_id?: string;
                nombre?: string;
                monto?: number;
            }[];
            /** @description Total monthly amount */
            total_mes?: number;
            /** @enum {string} */
            currency?: "USD" | "EUR" | "MXN";
        };
        PayrollIngest: {
            /** @description Month in YYYY-MM format */
            mes: string;
            /** @description Total payroll amount */
            nomina_total: number;
            /** @description Payroll breakdown by category */
            desglose?: {
                /** @description Engineers payroll */
                ingenieros?: number;
                /** @description SDM payroll */
                sdm?: number;
            };
            /** @description Source system (e.g., SAP_HR) */
            source?: string;
            /**
             * Format: email
             * @description User who uploaded the data
             */
            uploaded_by?: string;
        };
        CierreMes: {
            /** @description Month in YYYY-MM format */
            mes?: string;
            /** @description Coverage percentage (ingresos/nomina * 100) */
            cobertura?: number;
            /** @description Total payroll for the month */
            nomina?: number;
            /** @description Total invoiced revenue */
            ingresos_facturados?: number;
            /** @description Difference between revenue and payroll */
            gap?: number;
            /** @description Generated alerts */
            alertas?: {
                type?: string;
                /** @enum {string} */
                severity?: "critical" | "warning" | "info";
                message?: string;
            }[];
            /** Format: date-time */
            closed_at?: string;
            /** Format: email */
            closed_by?: string;
        };
        AdjustmentCreate: {
            project_id: string;
            /**
             * @description Type of adjustment
             * @enum {string}
             */
            tipo: "exceso" | "reduccion" | "reasignacion";
            /** @description Adjustment amount */
            monto: number;
            /** @description Source rubro (if reasignacion) */
            origen_rubro_id?: string;
            /** @description Destination rubro (if reasignacion) */
            destino_rubro_id?: string;
            /** @description Starting month for adjustment */
            fecha_inicio: string;
            /**
             * @description Distribution method
             * @enum {string}
             */
            metodo_distribucion?: "pro_rata_forward" | "pro_rata_all" | "single_month";
            /** @description Justification for adjustment */
            justificacion?: string;
            /** Format: email */
            solicitado_por: string;
        };
        Adjustment: components["schemas"]["AdjustmentCreate"] & {
            id: string;
            /** @enum {string} */
            estado: "pending_approval" | "approved" | "rejected";
            meses_impactados?: string[];
            distribucion?: {
                mes?: string;
                monto?: number;
            }[];
            /** Format: email */
            aprobado_por?: string;
            /** Format: date-time */
            aprobado_en?: string;
            /** Format: date-time */
            created_at: string;
        };
        AdjustmentList: {
            data?: components["schemas"]["Adjustment"][];
            total?: number;
            limit?: number;
            offset?: number;
        };
        MovementCreate: {
            project_id: string;
            rubro_id: string;
            /**
             * @description Movement type
             * @enum {string}
             */
            tipo: "gasto" | "ingreso" | "ajuste";
            /** @description Amount (positive for ingreso, can be negative for ajuste) */
            monto: number;
            /**
             * Format: date
             * @description Movement date
             */
            fecha: string;
            /** @description Movement description */
            descripcion: string;
            /** @description Provider ID (for gasto) */
            proveedor_id?: string;
            /**
             * Format: uri
             * @description URL to supporting documentation
             */
            evidencia_url?: string;
        };
        Movement: components["schemas"]["MovementCreate"] & {
            id: string;
            /** @enum {string} */
            estado: "pending" | "approved" | "rejected";
            /** Format: email */
            aprobado_por?: string;
            /** Format: date-time */
            aprobado_en?: string;
            /** Format: email */
            rechazado_por?: string;
            /** Format: date-time */
            rechazado_en?: string;
            comentarios?: string;
            motivo?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        MovementList: {
            data?: components["schemas"]["Movement"][];
            total?: number;
            limit?: number;
            offset?: number;
        };
        Approval: {
            /**
             * Format: email
             * @description Email of approver
             */
            aprobado_por: string;
            /** @description Approval comments */
            comentarios?: string;
        };
        Rejection: {
            /**
             * Format: email
             * @description Email of rejector
             */
            rechazado_por: string;
            /** @description Rejection reason */
            motivo: string;
        };
        ProviderCreate: {
            /** @description Provider name */
            nombre: string;
            /** @description Tax ID / RFC */
            tax_id: string;
            /**
             * @description Provider type
             * @enum {string}
             */
            tipo: "servicios" | "materiales" | "software" | "infraestructura";
            contacto_nombre?: string;
            /** Format: email */
            contacto_email?: string;
            contacto_telefono?: string;
            pais?: string;
            notas?: string;
        };
        Provider: components["schemas"]["ProviderCreate"] & {
            id: string;
            /** @enum {string} */
            estado: "active" | "inactive" | "suspended";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ProviderList: {
            data?: components["schemas"]["Provider"][];
            total?: number;
            limit?: number;
            offset?: number;
        };
        PrefacturaEvent: {
            /**
             * @description Type of webhook event
             * @enum {string}
             */
            event_type: "prefactura.created" | "prefactura.updated" | "prefactura.cancelled";
            /** @description Unique event identifier */
            event_id: string;
            /**
             * Format: date-time
             * @description Event timestamp
             */
            timestamp: string;
            data: {
                project_id: string;
                rubro_id: string;
                monto: number;
                mes: string;
                /** @description Invoice folio */
                folio?: string;
                descripcion?: string;
            };
        };
        Error: {
            /** @description Error code for programmatic handling */
            code: string;
            /** @description Human-readable error message */
            message: string;
            /** @description Additional error details */
            details?: {
                [key: string]: unknown;
            };
            /**
             * Format: date-time
             * @description Error timestamp
             */
            timestamp?: string;
        };
    };
    responses: {
        /** @description Bad Request - Invalid input parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "BAD_REQUEST",
                 *       "message": "Invalid request parameters",
                 *       "details": {
                 *         "field": "mod_total",
                 *         "error": "Must be a positive number"
                 *       },
                 *       "timestamp": "2025-10-31T03:55:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized - Missing or invalid authentication token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UNAUTHORIZED",
                 *       "message": "Authentication required",
                 *       "details": {
                 *         "reason": "Missing or invalid JWT token"
                 *       },
                 *       "timestamp": "2025-10-31T03:55:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Forbidden - Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "FORBIDDEN",
                 *       "message": "Insufficient permissions to access this resource",
                 *       "details": {
                 *         "required_group": "SDT",
                 *         "user_groups": [
                 *           "users"
                 *         ]
                 *       },
                 *       "timestamp": "2025-10-31T03:55:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not Found - Resource does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOT_FOUND",
                 *       "message": "Resource not found",
                 *       "details": {
                 *         "resource_type": "project",
                 *         "resource_id": "proj_invalid123"
                 *       },
                 *       "timestamp": "2025-10-31T03:55:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProjects: {
        parameters: {
            query?: {
                /** @description Filter by project status */
                status?: "active" | "completed" | "on_hold" | "cancelled";
                /** @description Maximum number of results to return */
                limit?: number;
                /** @description Number of results to skip for pagination */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of projects retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "id": "proj_7x9k2m4n8p",
                     *           "name": "Mobile Banking App MVP",
                     *           "code": "PROJ-2025-001",
                     *           "client": "Global Bank Corp",
                     *           "start_date": "2025-01-15",
                     *           "end_date": "2025-12-31",
                     *           "status": "active",
                     *           "mod_total": 1500000,
                     *           "currency": "USD",
                     *           "created_at": "2025-10-31T03:12:00Z",
                     *           "updated_at": "2025-10-31T03:12:00Z"
                     *         },
                     *         {
                     *           "id": "proj_3a5b7c9d1e",
                     *           "name": "ERP System Upgrade",
                     *           "code": "PROJ-2025-002",
                     *           "client": "Manufacturing Inc",
                     *           "start_date": "2025-02-01",
                     *           "end_date": "2025-11-30",
                     *           "status": "active",
                     *           "mod_total": 2800000,
                     *           "currency": "USD",
                     *           "created_at": "2025-10-30T10:00:00Z",
                     *           "updated_at": "2025-10-30T10:00:00Z"
                     *         }
                     *       ],
                     *       "total": 2,
                     *       "limit": 20,
                     *       "offset": 0
                     *     }
                     */
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Mobile Banking App MVP",
                 *       "code": "PROJ-2025-001",
                 *       "client": "Global Bank Corp",
                 *       "start_date": "2025-01-15",
                 *       "end_date": "2025-12-31",
                 *       "currency": "USD",
                 *       "mod_total": 1500000,
                 *       "description": "MVP for mobile banking application with core features"
                 *     }
                 */
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Project created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "proj_7x9k2m4n8p",
                     *       "name": "Mobile Banking App MVP",
                     *       "code": "PROJ-2025-001",
                     *       "client": "Global Bank Corp",
                     *       "start_date": "2025-01-15",
                     *       "end_date": "2025-12-31",
                     *       "currency": "USD",
                     *       "mod_total": 1500000,
                     *       "status": "active",
                     *       "description": "MVP for mobile banking application with core features",
                     *       "created_at": "2025-10-31T03:12:00Z",
                     *       "updated_at": "2025-10-31T03:12:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createHandoff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "mod_total": 1500000,
                 *       "pct_ingenieros": 65,
                 *       "pct_sdm": 35,
                 *       "aceptado_por": "juan.perez@company.com",
                 *       "fecha_handoff": "2025-11-01",
                 *       "notas": "Budget approved by PMO, team allocation confirmed"
                 *     }
                 */
                "application/json": components["schemas"]["Handoff"];
            };
        };
        responses: {
            /** @description Handoff processed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "handoff_2k4m6n8p0r",
                     *       "project_id": "proj_7x9k2m4n8p",
                     *       "status": "accepted",
                     *       "budget_ingenieros": 975000,
                     *       "budget_sdm": 525000,
                     *       "aceptado_por": "juan.perez@company.com",
                     *       "fecha_handoff": "2025-11-01",
                     *       "created_at": "2025-10-31T03:15:00Z"
                     *     }
                     */
                    "application/json": {
                        /** @description Handoff record ID */
                        id?: string;
                        /** @description Associated project ID */
                        project_id?: string;
                        /** @enum {string} */
                        status?: "accepted" | "pending" | "rejected";
                        /** @description Budget allocated to engineers */
                        budget_ingenieros?: number;
                        /** @description Budget allocated to SDM */
                        budget_sdm?: number;
                        /** Format: date-time */
                        created_at?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listRubros: {
        parameters: {
            query?: {
                /** @description Filter by execution type */
                tipo_ejecucion?: "mensual" | "puntual" | "por_hito";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rubros catalog retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "id": "rubro_1a2b3c4d5e",
                     *           "code": "RUBRO-001",
                     *           "nombre": "Desarrollo Backend",
                     *           "categoria": "Ingeniería",
                     *           "tipo_ejecucion": "mensual",
                     *           "descripcion": "Desarrollo y mantenimiento backend"
                     *         },
                     *         {
                     *           "id": "rubro_6f7g8h9i0j",
                     *           "code": "RUBRO-002",
                     *           "nombre": "Infraestructura Cloud",
                     *           "categoria": "Infraestructura",
                     *           "tipo_ejecucion": "mensual",
                     *           "descripcion": "Costos de infraestructura AWS/Azure"
                     *         },
                     *         {
                     *           "id": "rubro_k1l2m3n4o5",
                     *           "code": "RUBRO-003",
                     *           "nombre": "Capacitación Equipo",
                     *           "categoria": "Capacitación",
                     *           "tipo_ejecucion": "puntual",
                     *           "descripcion": "Cursos y certificaciones"
                     *         }
                     *       ],
                     *       "total": 3
                     *     }
                     */
                    "application/json": components["schemas"]["RubroList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listProjectRubros: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project rubros retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "id": "proj_rubro_7m8n9p0q1r",
                     *           "rubro_id": "rubro_1a2b3c4d5e",
                     *           "code": "RUBRO-001",
                     *           "nombre": "Desarrollo Backend",
                     *           "monto_total": 120000,
                     *           "tipo_ejecucion": "mensual",
                     *           "meses_programados": [
                     *             "2025-11",
                     *             "2025-12"
                     *           ]
                     *         }
                     *       ],
                     *       "total": 1
                     *     }
                     */
                    "application/json": components["schemas"]["RubroList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createProjectRubro: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "rubro_id": "rubro_1a2b3c4d5e",
                 *       "monto_total": 120000,
                 *       "tipo_ejecucion": "mensual",
                 *       "meses_programados": [
                 *         "2025-11",
                 *         "2025-12",
                 *         "2026-01",
                 *         "2026-02"
                 *       ],
                 *       "notas": "Equipo de 2 desarrolladores backend senior"
                 *     }
                 */
                "application/json": components["schemas"]["RubroCreate"];
            };
        };
        responses: {
            /** @description Rubro added to project successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "proj_rubro_7m8n9p0q1r",
                     *       "project_id": "proj_7x9k2m4n8p",
                     *       "rubro_id": "rubro_1a2b3c4d5e",
                     *       "code": "RUBRO-001",
                     *       "nombre": "Desarrollo Backend",
                     *       "monto_total": 120000,
                     *       "tipo_ejecucion": "mensual",
                     *       "meses_programados": [
                     *         "2025-11",
                     *         "2025-12",
                     *         "2026-01",
                     *         "2026-02"
                     *       ],
                     *       "monto_mensual": 30000,
                     *       "created_at": "2025-10-31T03:20:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Rubro"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    bulkUpdateAllocations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "allocations": [
                 *         {
                 *           "rubro_id": "rubro_1a2b3c4d5e",
                 *           "mes": "2025-11",
                 *           "monto_planeado": 30000
                 *         },
                 *         {
                 *           "rubro_id": "rubro_1a2b3c4d5e",
                 *           "mes": "2025-12",
                 *           "monto_planeado": 32000
                 *         },
                 *         {
                 *           "rubro_id": "rubro_6f7g8h9i0j",
                 *           "mes": "2025-11",
                 *           "monto_planeado": 15000
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["AllocationBulk"];
            };
        };
        responses: {
            /** @description Allocations updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "updated_count": 3,
                     *       "allocations": [
                     *         {
                     *           "rubro_id": "rubro_1a2b3c4d5e",
                     *           "mes": "2025-11",
                     *           "monto_planeado": 30000,
                     *           "status": "updated"
                     *         },
                     *         {
                     *           "rubro_id": "rubro_1a2b3c4d5e",
                     *           "mes": "2025-12",
                     *           "monto_planeado": 32000,
                     *           "status": "updated"
                     *         },
                     *         {
                     *           "rubro_id": "rubro_6f7g8h9i0j",
                     *           "mes": "2025-11",
                     *           "monto_planeado": 15000,
                     *           "status": "updated"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        /** @description Number of allocations updated */
                        updated_count?: number;
                        allocations?: {
                            rubro_id?: string;
                            mes?: string;
                            monto_planeado?: number;
                            status?: string;
                        }[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getProjectPlan: {
        parameters: {
            query: {
                /**
                 * @description Month in YYYY-MM format
                 * @example 2025-10
                 */
                mes: string;
            };
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Financial plan retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "project_id": "proj_7x9k2m4n8p",
                     *       "mes": "2025-10",
                     *       "plan_ing": 65000,
                     *       "plan_sdm": 35000,
                     *       "non_recurrentes": [
                     *         {
                     *           "rubro_id": "rubro_k1l2m3n4o5",
                     *           "nombre": "Capacitación Equipo",
                     *           "monto": 8000
                     *         },
                     *         {
                     *           "rubro_id": "rubro_p6q7r8s9t0",
                     *           "nombre": "Licencias Software",
                     *           "monto": 5000
                     *         }
                     *       ],
                     *       "total_mes": 113000,
                     *       "currency": "USD"
                     *     }
                     */
                    "application/json": components["schemas"]["PlanMes"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    ingestPayroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "mes": "2025-10",
                 *       "nomina_total": 98500,
                 *       "desglose": {
                 *         "ingenieros": 64000,
                 *         "sdm": 34500
                 *       },
                 *       "source": "SAP_HR",
                 *       "uploaded_by": "hr.admin@company.com"
                 *     }
                 */
                "application/json": components["schemas"]["PayrollIngest"];
            };
        };
        responses: {
            /** @description Payroll data accepted for processing */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "payroll_3x5y7z9a1b",
                     *       "mes": "2025-10",
                     *       "status": "processing",
                     *       "nomina_total": 98500,
                     *       "created_at": "2025-10-31T03:25:00Z"
                     *     }
                     */
                    "application/json": {
                        /** @description Payroll ingest record ID */
                        id?: string;
                        /** @description Month processed */
                        mes?: string;
                        /** @enum {string} */
                        status?: "processing" | "completed" | "failed";
                        /** @description Total payroll amount */
                        nomina_total?: number;
                        /** Format: date-time */
                        created_at?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    closeMonth: {
        parameters: {
            query: {
                /**
                 * @description Month to close in YYYY-MM format
                 * @example 2025-10
                 */
                mes: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Month closed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "mes": "2025-10",
                     *       "cobertura": 114.72,
                     *       "nomina": 98500,
                     *       "ingresos_facturados": 113000,
                     *       "gap": 15500,
                     *       "alertas": [
                     *         {
                     *           "type": "coverage_above_target",
                     *           "severity": "warning",
                     *           "message": "Coverage exceeded 110% target"
                     *         },
                     *         {
                     *           "type": "positive_gap",
                     *           "severity": "info",
                     *           "message": "Positive gap of $15,500"
                     *         }
                     *       ],
                     *       "closed_at": "2025-10-31T23:59:59Z",
                     *       "closed_by": "finance.manager@company.com"
                     *     }
                     */
                    "application/json": components["schemas"]["CierreMes"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getCoverageReport: {
        parameters: {
            query?: {
                /** @description Start date in YYYY-MM format */
                start_date?: string;
                /** @description End date in YYYY-MM format */
                end_date?: string;
                /** @description Filter by specific project */
                project_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coverage report retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "period": {
                     *         "start": "2025-01",
                     *         "end": "2025-10"
                     *       },
                     *       "summary": {
                     *         "avg_cobertura": 108.5,
                     *         "total_nomina": 985000,
                     *         "total_ingresos": 1068725
                     *       },
                     *       "monthly_data": [
                     *         {
                     *           "mes": "2025-10",
                     *           "cobertura": 114.72,
                     *           "nomina": 98500,
                     *           "ingresos_facturados": 113000,
                     *           "gap": 15500
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        period?: {
                            start?: string;
                            end?: string;
                        };
                        summary?: {
                            avg_cobertura?: number;
                            total_nomina?: number;
                            total_ingresos?: number;
                        };
                        monthly_data?: components["schemas"]["CierreMes"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAdjustments: {
        parameters: {
            query?: {
                /** @description Filter by project */
                project_id?: string;
                /** @description Filter by approval state */
                estado?: "pending_approval" | "approved" | "rejected";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Adjustments list retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "id": "adj_9c1d3e5f7g",
                     *           "project_id": "proj_7x9k2m4n8p",
                     *           "tipo": "exceso",
                     *           "monto": 1000000,
                     *           "fecha_inicio": "2025-11",
                     *           "solicitado_por": "pm.leader@company.com",
                     *           "estado": "approved",
                     *           "created_at": "2025-10-31T03:30:00Z"
                     *         }
                     *       ],
                     *       "total": 1,
                     *       "limit": 20,
                     *       "offset": 0
                     *     }
                     */
                    "application/json": components["schemas"]["AdjustmentList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAdjustment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "project_id": "proj_7x9k2m4n8p",
                 *       "tipo": "exceso",
                 *       "monto": 1000000,
                 *       "origen_rubro_id": "rubro_1a2b3c4d5e",
                 *       "fecha_inicio": "2025-11",
                 *       "metodo_distribucion": "pro_rata_forward",
                 *       "justificacion": "Ampliación de alcance aprobada por cliente",
                 *       "solicitado_por": "pm.leader@company.com"
                 *     }
                 */
                "application/json": components["schemas"]["AdjustmentCreate"];
            };
        };
        responses: {
            /** @description Adjustment created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "adj_9c1d3e5f7g",
                     *       "project_id": "proj_7x9k2m4n8p",
                     *       "tipo": "exceso",
                     *       "monto": 1000000,
                     *       "estado": "pending_approval",
                     *       "origen_rubro_id": "rubro_1a2b3c4d5e",
                     *       "fecha_inicio": "2025-11",
                     *       "metodo_distribucion": "pro_rata_forward",
                     *       "justificacion": "Ampliación de alcance aprobada por cliente",
                     *       "solicitado_por": "pm.leader@company.com",
                     *       "meses_impactados": [
                     *         "2025-11",
                     *         "2025-12",
                     *         "2026-01"
                     *       ],
                     *       "distribucion": [
                     *         {
                     *           "mes": "2025-11",
                     *           "monto": 333333.33
                     *         },
                     *         {
                     *           "mes": "2025-12",
                     *           "monto": 333333.33
                     *         },
                     *         {
                     *           "mes": "2026-01",
                     *           "monto": 333333.34
                     *         }
                     *       ],
                     *       "created_at": "2025-10-31T03:30:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Adjustment"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listMovements: {
        parameters: {
            query?: {
                /** @description Filter by project */
                project_id?: string;
                /** @description Filter by approval state */
                estado?: "pending" | "approved" | "rejected";
                /** @description Filter by movement type */
                tipo?: "gasto" | "ingreso" | "ajuste";
                /** @description Start date filter (YYYY-MM-DD) */
                start_date?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Movements list retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "id": "mov_4n5o6p7q8r",
                     *           "project_id": "proj_7x9k2m4n8p",
                     *           "rubro_id": "rubro_1a2b3c4d5e",
                     *           "tipo": "gasto",
                     *           "monto": 25000,
                     *           "estado": "pending",
                     *           "fecha": "2025-10-28",
                     *           "descripcion": "Pago consultoría especializada Q4",
                     *           "created_at": "2025-10-31T03:35:00Z",
                     *           "updated_at": "2025-10-31T03:35:00Z"
                     *         }
                     *       ],
                     *       "total": 1,
                     *       "limit": 50,
                     *       "offset": 0
                     *     }
                     */
                    "application/json": components["schemas"]["MovementList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createMovement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "project_id": "proj_7x9k2m4n8p",
                 *       "rubro_id": "rubro_1a2b3c4d5e",
                 *       "tipo": "gasto",
                 *       "monto": 25000,
                 *       "fecha": "2025-10-28",
                 *       "descripcion": "Pago consultoría especializada Q4",
                 *       "proveedor_id": "prov_8h9i0j1k2l",
                 *       "evidencia_url": "https://storage.example.com/invoices/INV-2025-1028.pdf"
                 *     }
                 */
                "application/json": components["schemas"]["MovementCreate"];
            };
        };
        responses: {
            /** @description Movement created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "mov_4n5o6p7q8r",
                     *       "project_id": "proj_7x9k2m4n8p",
                     *       "rubro_id": "rubro_1a2b3c4d5e",
                     *       "tipo": "gasto",
                     *       "monto": 25000,
                     *       "fecha": "2025-10-28",
                     *       "estado": "pending",
                     *       "descripcion": "Pago consultoría especializada Q4",
                     *       "proveedor_id": "prov_8h9i0j1k2l",
                     *       "created_at": "2025-10-31T03:35:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Movement"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    approveMovement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Movement ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "aprobado_por": "finance.manager@company.com",
                 *       "comentarios": "Aprobado - documentación correcta"
                 *     }
                 */
                "application/json": components["schemas"]["Approval"];
            };
        };
        responses: {
            /** @description Movement approved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "mov_4n5o6p7q8r",
                     *       "project_id": "proj_7x9k2m4n8p",
                     *       "rubro_id": "rubro_1a2b3c4d5e",
                     *       "tipo": "gasto",
                     *       "monto": 25000,
                     *       "fecha": "2025-10-28",
                     *       "descripcion": "Pago consultoría especializada Q4",
                     *       "estado": "approved",
                     *       "aprobado_por": "finance.manager@company.com",
                     *       "aprobado_en": "2025-10-31T03:40:00Z",
                     *       "comentarios": "Aprobado - documentación correcta",
                     *       "created_at": "2025-10-31T03:35:00Z",
                     *       "updated_at": "2025-10-31T03:40:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Movement"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    rejectMovement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Movement ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "rechazado_por": "finance.manager@company.com",
                 *       "motivo": "Documentación incompleta - falta factura original"
                 *     }
                 */
                "application/json": components["schemas"]["Rejection"];
            };
        };
        responses: {
            /** @description Movement rejected successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "mov_4n5o6p7q8r",
                     *       "project_id": "proj_7x9k2m4n8p",
                     *       "rubro_id": "rubro_1a2b3c4d5e",
                     *       "tipo": "gasto",
                     *       "monto": 25000,
                     *       "fecha": "2025-10-28",
                     *       "descripcion": "Pago consultoría especializada Q4",
                     *       "estado": "rejected",
                     *       "rechazado_por": "finance.manager@company.com",
                     *       "rechazado_en": "2025-10-31T03:40:00Z",
                     *       "motivo": "Documentación incompleta - falta factura original",
                     *       "created_at": "2025-10-31T03:35:00Z",
                     *       "updated_at": "2025-10-31T03:40:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Movement"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                /** @description Filter by project */
                project_id?: string;
                /** @description Filter by severity level */
                severity?: "critical" | "warning" | "info";
                /** @description Filter by alert type */
                type?: "budget_overrun" | "coverage_low" | "payment_pending" | "allocation_missing";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alerts retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "id": "alert_7s8t9u0v1w",
                     *           "project_id": "proj_7x9k2m4n8p",
                     *           "type": "budget_overrun",
                     *           "severity": "warning",
                     *           "message": "Rubro 'Desarrollo Backend' at 85% of budget",
                     *           "details": {
                     *             "rubro_id": "rubro_1a2b3c4d5e",
                     *             "budget": 120000,
                     *             "spent": 102000,
                     *             "percentage": 85
                     *           },
                     *           "created_at": "2025-10-30T10:00:00Z"
                     *         },
                     *         {
                     *           "id": "alert_2x3y4z5a6b",
                     *           "project_id": "proj_3a5b7c9d1e",
                     *           "type": "coverage_low",
                     *           "severity": "critical",
                     *           "message": "Coverage below 100% for October",
                     *           "details": {
                     *             "mes": "2025-10",
                     *             "cobertura": 92.3,
                     *             "target": 105
                     *           },
                     *           "created_at": "2025-10-31T01:00:00Z"
                     *         }
                     *       ],
                     *       "total": 2
                     *     }
                     */
                    "application/json": {
                        data?: {
                            id?: string;
                            project_id?: string;
                            type?: string;
                            severity?: string;
                            message?: string;
                            details?: Record<string, never>;
                            /** Format: date-time */
                            created_at?: string;
                        }[];
                        total?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listProviders: {
        parameters: {
            query?: {
                /** @description Filter by provider type */
                tipo?: "servicios" | "materiales" | "software" | "infraestructura";
                /** @description Filter by provider status */
                estado?: "active" | "inactive" | "suspended";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Providers list retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "id": "prov_8h9i0j1k2l",
                     *           "nombre": "TechConsulting Solutions LLC",
                     *           "tax_id": "RFC-987654321",
                     *           "tipo": "servicios",
                     *           "estado": "active",
                     *           "created_at": "2025-10-31T03:45:00Z"
                     *         },
                     *         {
                     *           "id": "prov_3m4n5o6p7q",
                     *           "nombre": "Cloud Infrastructure Corp",
                     *           "tax_id": "RFC-123456789",
                     *           "tipo": "infraestructura",
                     *           "estado": "active",
                     *           "created_at": "2025-10-30T09:00:00Z"
                     *         }
                     *       ],
                     *       "total": 2,
                     *       "limit": 20,
                     *       "offset": 0
                     *     }
                     */
                    "application/json": components["schemas"]["ProviderList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "nombre": "TechConsulting Solutions LLC",
                 *       "tax_id": "RFC-987654321",
                 *       "tipo": "servicios",
                 *       "contacto_nombre": "María García",
                 *       "contacto_email": "maria.garcia@techconsulting.com",
                 *       "contacto_telefono": "+1-555-0123",
                 *       "pais": "USA",
                 *       "notas": "Proveedor preferente para consultoría especializada"
                 *     }
                 */
                "application/json": components["schemas"]["ProviderCreate"];
            };
        };
        responses: {
            /** @description Provider created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "prov_8h9i0j1k2l",
                     *       "nombre": "TechConsulting Solutions LLC",
                     *       "tax_id": "RFC-987654321",
                     *       "tipo": "servicios",
                     *       "contacto_nombre": "María García",
                     *       "contacto_email": "maria.garcia@techconsulting.com",
                     *       "contacto_telefono": "+1-555-0123",
                     *       "pais": "USA",
                     *       "estado": "active",
                     *       "created_at": "2025-10-31T03:45:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Provider"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    prefacturaWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "event_type": "prefactura.created",
                 *       "event_id": "evt_9r8s7t6u5v",
                 *       "timestamp": "2025-10-31T03:50:00Z",
                 *       "data": {
                 *         "project_id": "proj_7x9k2m4n8p",
                 *         "rubro_id": "rubro_1a2b3c4d5e",
                 *         "monto": 30000,
                 *         "mes": "2025-11",
                 *         "folio": "PREFACT-2025-110001",
                 *         "descripcion": "Desarrollo backend - Noviembre 2025"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["PrefacturaEvent"];
            };
        };
        responses: {
            /** @description Webhook event accepted for processing */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "accepted",
                     *       "event_id": "evt_9r8s7t6u5v",
                     *       "message": "Prefactura event queued for processing"
                     *     }
                     */
                    "application/json": {
                        /** @enum {string} */
                        status?: "accepted" | "processing";
                        event_id?: string;
                        message?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
