name: Generate Cognito JWT
description: Authenticates with AWS Cognito and generates a JWT access token

inputs:
  user_pool_id:
    description: "Cognito User Pool ID"
    required: true
  client_id:
    description: "Cognito Web Client ID"
    required: true
  username:
    description: "Cognito username"
    required: true
  password:
    description: "Cognito password"
    required: true
  aws_region:
    description: "AWS region"
    required: true

outputs:
  access_token:
    description: "JWT ID token (with aud claim for API Gateway authorizer)"
    value: ${{ steps.auth.outputs.access_token }}

runs:
  using: composite
  steps:
    - name: Authenticate and get JWT
      id: auth
      shell: bash
      run: |
        set -euo pipefail

        # Authenticate with Cognito and get tokens
        AUTH_RESPONSE=$(aws cognito-idp initiate-auth \
          --region "${{ inputs.aws_region }}" \
          --auth-flow USER_PASSWORD_AUTH \
          --client-id "${{ inputs.client_id }}" \
          --auth-parameters "USERNAME=${{ inputs.username }},PASSWORD=${{ inputs.password }}" \
          --query 'AuthenticationResult' \
          --output json)

        # Extract ID token (has aud claim for JWT authorizer validation)
        # Note: API Gateway JWT authorizer requires aud claim in token; AccessToken lacks this
        ID_TOKEN=$(echo "$AUTH_RESPONSE" | jq -r '.IdToken')

        if [ -z "$ID_TOKEN" ] || [ "$ID_TOKEN" = "null" ] || [ "$ID_TOKEN" = "" ]; then
          echo "❌ Failed to obtain ID token"
          exit 1
        fi

        echo "✅ Successfully obtained JWT ID token"
        # Mask the token to prevent it from appearing in logs
        echo "::add-mask::$ID_TOKEN"
        printf 'access_token=%s\n' "$ID_TOKEN" >> "$GITHUB_OUTPUT"
