AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Finanzas SD API (HTTP API + Cognito JWT + DynamoDB + EventBridge) – dev stage

Parameters:
  CognitoUserPoolArn:
    Type: String
    Description: Existing Cognito User Pool ARN (from acta-ui)
  CognitoUserPoolId:
    Type: String
    Description: Existing Cognito User Pool ID (from acta-ui) - e.g., us-east-2_FyHLtOhiY
    Default: us-east-2_FyHLtOhiY
  StageName:
    Type: String
    Default: dev
  TablePrefix:
    Type: String
    Default: finz_

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 15
    MemorySize: 256
    Architectures: [x86_64]
    Tracing: Active
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps
        TABLE_PROJECTS: !Sub ${TablePrefix}projects
        TABLE_RUBROS: !Sub ${TablePrefix}rubros
        TABLE_ALLOC: !Sub ${TablePrefix}allocations
        TABLE_PAYROLL: !Sub ${TablePrefix}payroll_actuals
        TABLE_ADJ: !Sub ${TablePrefix}adjustments
        TABLE_ALERTS: !Sub ${TablePrefix}alerts
        TABLE_PROVIDERS: !Sub ${TablePrefix}providers
        TABLE_AUDIT: !Sub ${TablePrefix}audit_log

Resources:
  # ========== DynamoDB tables ==========
  ProjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TablePrefix}projects
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: pk, AttributeType: S }
        - { AttributeName: sk, AttributeType: S }
      KeySchema:
        - { AttributeName: pk, KeyType: HASH }
        - { AttributeName: sk, KeyType: RANGE }

  RubrosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TablePrefix}rubros
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: pk, AttributeType: S }
        - { AttributeName: sk, AttributeType: S }
      KeySchema:
        - { AttributeName: pk, KeyType: HASH }
        - { AttributeName: sk, KeyType: RANGE }

  AllocationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TablePrefix}allocations
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: pk, AttributeType: S }
        - { AttributeName: sk, AttributeType: S }
      KeySchema:
        - { AttributeName: pk, KeyType: HASH }
        - { AttributeName: sk, KeyType: RANGE }

  PayrollTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TablePrefix}payroll_actuals
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: pk, AttributeType: S }
        - { AttributeName: sk, AttributeType: S }
      KeySchema:
        - { AttributeName: pk, KeyType: HASH }
        - { AttributeName: sk, KeyType: RANGE }

  AdjustmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TablePrefix}adjustments
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: pk, AttributeType: S }
        - { AttributeName: sk, AttributeType: S }
      KeySchema:
        - { AttributeName: pk, KeyType: HASH }
        - { AttributeName: sk, KeyType: RANGE }

  AlertsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TablePrefix}alerts
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: pk, AttributeType: S }
        - { AttributeName: sk, AttributeType: S }
      KeySchema:
        - { AttributeName: pk, KeyType: HASH }
        - { AttributeName: sk, KeyType: RANGE }

  ProvidersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TablePrefix}providers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: pk, AttributeType: S }
        - { AttributeName: sk, AttributeType: S }
      KeySchema:
        - { AttributeName: pk, KeyType: HASH }
        - { AttributeName: sk, KeyType: RANGE }

  AuditTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TablePrefix}audit_log
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: pk, AttributeType: S }
        - { AttributeName: sk, AttributeType: S }
      KeySchema:
        - { AttributeName: pk, KeyType: HASH }
        - { AttributeName: sk, KeyType: RANGE }

  # ========== HTTP API with Cognito JWT ==========
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      CorsConfiguration:
        AllowMethods: [GET,POST,PUT,OPTIONS]
        AllowOrigins: ['*']
        AllowHeaders: ['Authorization','Content-Type']
      Auth:
        Authorizers:
          CognitoJwt:
            JwtConfiguration:
              issuer: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPoolId}
            IdentitySource: "$request.header.Authorization"
        DefaultAuthorizer: CognitoJwt

  # ========== Lambdas ==========
  HealthFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - handlers/health.ts
    Properties:
      CodeUri: src/
      Handler: health.handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Health:
          Type: HttpApi
          Properties: { Path: /health, Method: GET, ApiId: !Ref Api }

  ProjectsFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - handlers/projects.ts
    Properties:
      CodeUri: src/
      Handler: projects.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref ProjectsTable
      Events:
        CreateProject:
          Type: HttpApi
          Properties: { Path: /projects, Method: POST, ApiId: !Ref Api }
        ListProjects:
          Type: HttpApi
          Properties: { Path: /projects, Method: GET, ApiId: !Ref Api }

  CatalogFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - handlers/catalog.ts
    Properties:
      CodeUri: src/
      Handler: catalog.handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ListRubros:
          Type: HttpApi
          Properties: { Path: /catalog/rubros, Method: GET, ApiId: !Ref Api }

  HandoffFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - handlers/handoff.ts
    Properties:
      CodeUri: src/
      Handler: handoff.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref ProjectsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditTable
      Events:
        Handoff:
          Type: HttpApi
          Properties: 
            Path: "/projects/{id}/handoff"
            Method: POST
            ApiId: !Ref Api

  # TODO: Implement PEP-3 monthly alert logic for budget variance detection
  # Currently reuses health handler as placeholder
  AlertsPep3Fn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - handlers/health.ts
    Properties:
      CodeUri: src/
      Handler: health.handler
      Policies:
        - AWSLambdaBasicExecutionRole

  # R1 MVP endpoints - stubbed for initial slice
  RubrosFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - handlers/rubros.ts
    Properties:
      CodeUri: src/
      Handler: rubros.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref RubrosTable
      Events:
        CreateRubro:
          Type: HttpApi
          Properties: 
            Path: "/projects/{id}/rubros"
            Method: POST
            ApiId: !Ref Api
        ListRubros:
          Type: HttpApi
          Properties: 
            Path: "/projects/{id}/rubros"
            Method: GET
            ApiId: !Ref Api

  AllocationsFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - handlers/allocations.ts
    Properties:
      CodeUri: src/
      Handler: allocations.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref AllocationsTable
      Events:
        BulkAllocations:
          Type: HttpApi
          Properties: 
            Path: "/projects/{id}/allocations:bulk"
            Method: PUT
            ApiId: !Ref Api

  PlanFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - handlers/plan.ts
    Properties:
      CodeUri: src/
      Handler: plan.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: !Ref ProjectsTable
        - DynamoDBReadPolicy:
            TableName: !Ref AllocationsTable
        - DynamoDBReadPolicy:
            TableName: !Ref PayrollTable
        - DynamoDBReadPolicy:
            TableName: !Ref AdjustmentsTable
      Events:
        GetPlan:
          Type: HttpApi
          Properties: 
            Path: "/projects/{id}/plan"
            Method: GET
            ApiId: !Ref Api

  PayrollFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - handlers/payroll.ts
    Properties:
      CodeUri: src/
      Handler: payroll.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref PayrollTable
      Events:
        IngestPayroll:
          Type: HttpApi
          Properties: { Path: /payroll/ingest, Method: POST, ApiId: !Ref Api }

  CloseMonthFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - handlers/close-month.ts
    Properties:
      CodeUri: src/
      Handler: close-month.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref ProjectsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AllocationsTable
      Events:
        CloseMonth:
          Type: HttpApi
          Properties: { Path: /close-month, Method: POST, ApiId: !Ref Api }

  AdjustmentsFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - handlers/adjustments.ts
    Properties:
      CodeUri: src/
      Handler: adjustments.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref AdjustmentsTable
      Events:
        CreateAdjustment:
          Type: HttpApi
          Properties: { Path: /adjustments, Method: POST, ApiId: !Ref Api }
        ListAdjustments:
          Type: HttpApi
          Properties: { Path: /adjustments, Method: GET, ApiId: !Ref Api }

  AlertsFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - handlers/alerts.ts
    Properties:
      CodeUri: src/
      Handler: alerts.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: !Ref AlertsTable
      Events:
        GetAlerts:
          Type: HttpApi
          Properties: { Path: /alerts, Method: GET, ApiId: !Ref Api }

  ProvidersFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - handlers/providers.ts
    Properties:
      CodeUri: src/
      Handler: providers.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref ProvidersTable
      Events:
        CreateProvider:
          Type: HttpApi
          Properties: { Path: /providers, Method: POST, ApiId: !Ref Api }
        ListProviders:
          Type: HttpApi
          Properties: { Path: /providers, Method: GET, ApiId: !Ref Api }

  PrefacturasFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - handlers/prefacturas.ts
    Properties:
      CodeUri: src/
      Handler: prefacturas.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditTable
      Events:
        WebhookPost:
          Type: HttpApi
          Properties: { Path: /prefacturas/webhook, Method: POST, ApiId: !Ref Api }
        WebhookGet:
          Type: HttpApi
          Properties: { Path: /prefacturas/webhook, Method: GET, ApiId: !Ref Api }

  Pep3Rule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 8 1 * ? *)  # monthly, 8am UTC 1st
      State: ENABLED
      Targets:
        - Arn: !GetAtt AlertsPep3Fn.Arn
          Id: pep3-target
  Pep3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AlertsPep3Fn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt Pep3Rule.Arn

Outputs:
  FinzApiId:
    Description: HTTP API ID
    Value: !Ref Api
    Export:
      Name: finz-api-id
  FinzApiUrl:
    Description: HTTP API URL
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${StageName}
    Export:
      Name: finz-api-url
